import jquery from 'jquery';
window.$ = window.jQuery = jquery;
import 'jquery-ui';
import 'admin-lte/plugins/fastclick/fastclick.min';
require('admin-lte/plugins/slimScroll/jquery.slimscroll.min');
require('admin-lte/dist/js/app.min');
import 'admin-lte/bootstrap/css/bootstrap.min.css';
import 'admin-lte/dist/css/AdminLTE.min.css';
import 'admin-lte/dist/css/skins/_all-skins.css';
import 'admin-lte/plugins/iCheck/flat/blue.css';
import 'font-awesome/css/font-awesome.min.css';
import 'ionicons/dist/css/ionicons.min.css';
import './custom.css';